package headset.events;

public enum HeadsetDataTypes {
  //FIXME: THE UNKNOWN TYPE IS NOT USED IN THE CODE IT'S JUST FOR TESTING PURPOSES
  UNKNOWN,
  RAW,
  BAND_POWER,
  ATTENTION,
  MEDITATION,
  BLINK,
  SIGNAL_QUALITY
}
