package headset.events.nskAlgo;

public enum AlgoEventTypes {
  //FIXME: THE UNKNOWN TYPE IS NOT USED IN THE CODE IT'S JUST FOR TESTING PURPOSES
  UNKNOWN,
  BAND_POWER,
  ATTENTION,
  MEDITATION,
  BLINK,
  SIGNAL_QUALITY,
  STATE
}
